select 
`m`.`menu` AS `id`,
`m`.`name` AS `name`,
`m`.`node_left` AS `node_left`,
`m`.`node_right` AS `node_right`,
`m`.`slug` AS `slug`,
`m`.`l10n` AS `l10n`,
'menu' AS `slug_type`,
`m`.`website` AS `website`,
`m`.`d_store` AS `d_store`,
`m`.`family` AS `family`,
`m`.`brand` AS `brand`,
`m`.`vehicle` AS `vehicle`,
`m`.`category` AS `category`,
`m`.`department` AS `department`,
`m`.`behavior` AS `behavior`,
`m`.`clothing_category` AS `clothing_category`,
`m`.`depth` AS `depth`,
NULL AS `license_id`,
case when `m`.`website` = 6 then 1 else 2 end AS `workspace`,
0 AS `redirection`,
NULL AS `status_code`,
NULL AS `location`,
`m`.`display` AS `display` 
from `vue_menu_items` `m` 
where `m`.`page` is null and `m`.`in_progress` is null 
union all select 
`l`.`website_license` AS `id`,
NULL AS `name`,
NULL AS `node_left`,
NULL AS `node_right`,
`l`.`slug` AS `slug`,
`l`.`l10n` AS `l10n`,
'license' AS `slug_type`,
`wl`.`website` AS `website`,
NULL AS `d_store`,
NULL AS `family`,
NULL AS `brand`,
NULL AS `vehicle`,
NULL AS `category`,
NULL AS `department`,
NULL AS `behavior`,
NULL AS `clothing_category`,
NULL AS `depth`,`wl`.`license` AS `license_id`,
case when `wl`.`website` = 6 then 1 else 2 end AS `workspace`,
0 AS `redirection`,
NULL AS `status_code`,
NULL AS `location`,
NULL AS `display` 
from (`license_l10ns` `l` 
	join `website_licenses` `wl` on(`wl`.`id` = `l`.`website_license`)) 
union all select `cat`.`id` AS `id`,
`cat_l10n`.`designation` AS `name`,
`cat`.`node_left` AS `node_left`,
`cat`.`node_right` AS `node_right`,
`cat_l10n`.`slug` AS `slug`,
`cat_l10n`.`l10n` AS `l10n`,
'section' AS `slug_type`,
case when `cat`.`workspace` = 2 then 5 else 6 end AS `website`,
(select `c`.`department_store` from `categories` `c` where `c`.`node_left` <= `cat`.`node_left` and `c`.`node_right` >= `cat`.`node_right` and `c`.`workspace` = `cat`.`workspace` and `c`.`department_store` is not null order by `c`.`node_left` desc limit 1) AS `d_store`,
case when `cat`.`workspace` = 2 then `v_cat`.`family` else NULL end AS `family`,
case when `cat`.`workspace` = 2 then `v_cat`.`brand` else NULL end AS `brand`,
case when `cat`.`workspace` = 2 then `v_cat`.`vehicle` else NULL end AS `vehicle`,
NULL AS `category`,
NULL AS `department`,
case when `cat`.`workspace` = 2 then `behaviors`.`name` else NULL end AS `behavior`,
NULL AS `clothing_category`,
`cat`.`depth` AS `depth`,
NULL AS `licence_id`,
`cat`.`workspace` AS `workspace`,
0 AS `redirection`,
NULL AS `status_code`,
NULL AS `location`,
NULL AS `display` from ((((`category_l10ns` `cat_l10n` 
	join `categories` `cat` on(`cat`.`id` = `cat_l10n`.`category`)) 
left join `vehicle_categories` `v_cat` on(`v_cat`.`id` = `cat`.`id`)) 
left join `behaviors` on(`behaviors`.`id` = `v_cat`.`behavior`)) 
left join `appareal_categories` `a_cat` on(`a_cat`.`id` = `cat`.`id`)) 